### ISSUE TITLE
Feedback 2

### ISSUE THREAD

**Issue by tincho282** [hernancarreno01/ML2#1]
- [x] 1 - Cumple (Diseño acorde a lo visto en clase)
- [x] 2 - Cumple (Se ajusta a los requisitos del footer)
- [x] 3 - Cumple (Se ajusta a diferentes resoluciones)
- [ ] 4 - Cumple (Cuenta con formulario de registro)
- [x] 5 - Cumple (Cuenta con formulario de login)
- [ ] 6 -
- [x] 7 - No cumple (No hay formularios de búsqueda)
- [ ] 8 - Cumple (Hay estilos y animaciones)
- [x] 9 - El proyecto esta muy bueno, todo en su debido lugar y funcionando correctamente ✨
- [x] 10 - Creo que no hay cosas a mejorar, en líneas generales el trabajo se encuentra muy bien. 😊

**Comment by hernancarreno01** [comment]
Gracias @tincho282
