### ISSUE TITLE
Peer Review - Ibañez Alexis

### ISSUE THREAD

**Issue by Alexxis8** [hernancarreno01/ML2#2]
1- Cumple con todo lo pedido.
2- Cumple con todo lo pedido.
3- El sitio se adapta a distintas resoluciones de pantalla.
4- El sitio cuenta con un formulario de registro de usuario, Cumple con lo pedido.
5- El sitio cuenta con un formulario de login, Cumple con lo pedido.
7- El search bar no es un formulario, es un div, pero en aspecto de diseño esta correcto.
8- Se utilizan animaciones y propiedades de transición de CSS, Cumple con lo pedido.
9- Me gustaron los textos "Ver descripcion" de los articulos y los diseños de los formularios.
10- Lo que veo a mejorar es solamente que cuando se haga click en el logo se redireccione a la vista del home, solamente eso.

**Comment by hernancarreno01** [comment]
Gracias!
